# Generated by Django 2.1 on 2019-04-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lName', models.CharField(max_length=50)),
                ('teams', models.IntegerField()),
            ],
        ),
    ]
