# Generated by Django 2.1 on 2019-04-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0002_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='image_url',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
