# Generated by Django 2.1 on 2019-04-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0003_auto_20190417_1028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nations',
            new_name='Nation',
        ),
    ]
